### ISSUE TITLE
A suggestion

### ISSUE THREAD

**Issue by sagnikbanerjee15** [griffithlab/regtools#104]
Hello,

Regtools is a wonderful software and I have been using it to extract junctions from aligned bamfiles. It would be great if you could also output whether the junctions are cannonical or non-cannonical.

Thank you.

**Comment by yang-yangfeng** [comment]
Hi @sagnikbanerjee15, thank you! We agree that knowing whether junctions are canonical is important and we've tried to make this clear in the output by labeling the junctions as "DA" for known "donor" and "acceptor". Unknown junctions are labelled as D/A/N/NDA (see https://regtools.readthedocs.io/en/latest/commands/junctions-annotate/#notes). Apologies if this was confusing.
