### ISSUE TITLE
0.5.2 version in CMakeLists.txt?

### ISSUE THREAD

**Issue by cjhull** [griffithlab/regtools#129]
Hello,
I grabbed and compiled the 0.5.2 zip today, and noticed that when run, the binary reports it's version as 0.5.1:

> Program:	regtools
> Version:	0.5.1

I suspect that this is just a mistake in not updating https://github.com/griffithlab/regtools/blob/0.5.2/CMakeLists.txt, however I wanted to check to make sure I'm giving my customer the correct version.

Thank you.

**Comment by yang-yangfeng** [comment]
The zip is correctly labelled is 0.5.2 - we forgot to change the CMakeLists. Thank you for bring this to our attention! #131 addresses this issue.
