### ISSUE TITLE
Error from Running leafcutter_cluster_regtools.py for Intron Clustering 

### ISSUE THREAD

**Issue by Aynur31** [griffithlab/regtools#141]
Hello, 
I am new to bioinformatics. I am trying to do differential splicing analysis for mouse RNA-Seq data. 
I followed this  material- [https://davidaknowles.github.io/leafcutter/articles/Usage.html].
The following my code and error message.
`$ python /kuacc/users/akashgari19/apps/leafcutter/scripts/leafcutter_cluster_regtools.py -j test_juncfiles.txt -m 50 -o testYRIvsEU -l 500000` 
I already added strand specificity in converting Bams to Juncs step. I also tried strand specificity on the above code, but did not work. 
Can you please help me with this issue?
Thank you very much.

**Comment by malachig** [comment]
I don't see an error message here?  Just the command that you ran.  I was not aware of this use of regtools by the leafcutter workflow.  Nice to see that.

**Comment by Aynur31** [comment]
Sorry for miscommunication. I was also showing my error message on regtools google group. 
for bamfile in `ls $outdir/CON-2Aligned.sortedByCoord.out.bam`; do
    echo Converting $bamfile to $bamfile.junc
    samtools index $bamfile
    /kuacc/users/akashgari19/apps/regtools/build/regtools junctions extract -a 8 -m 50 -M 500000 -s 1 $bamfile -o $bamfile.junc
    echo $bamfile.junc >> test_juncfiles.txt
done
In this way , I got .juncfiles. Note, I already included strand information.Then ran the following command.Below is the code along with error message. 
$ python /kuacc/users/akashgari19/apps/leafcutter/scripts/leafcutter_cluster_regtools.py -j test_juncfiles.txt -m 50 -o testYRIvsEU -l 500000
scanning /kuacc/users/akashgari19/CutterLeaf_STAR_Mapping/con2_mapping/CON-2Aligned.sortedByCoord.out.bam.junc...
Parsing...
X:+..17:+..17:-..9:?..16:-..1:?..Y:-..18:+..19:?..Traceback (most recent call last):
  File "/kuacc/users/akashgari19/apps/leafcutter/scripts/leafcutter_cluster_regtools.py", line 497, in <module>
    main(options, libl)
  File "/kuacc/users/akashgari19/apps/leafcutter/scripts/leafcutter_cluster_regtools.py", line 14, in main
    pool_junc_reads(libl, options)
  File "/kuacc/users/akashgari19/apps/leafcutter/scripts/leafcutter_cluster_regtools.py", line 68, in pool_junc_reads
    clu = cluster_intervals(read_ks)[0]
  File "/kuacc/users/akashgari19/apps/leafcutter/scripts/leafcutter_cluster_regtools.py", line 316, in cluster_intervals
    current = E[0]
IndexError: list index out of range
Below is my file. 
 head CON-2Aligned.sortedByCoord.out.bam.junc
1	4495058	4676205	JUNC00000001	2	-	4495058	4676205	255,0,0	2	18,54	0,181093
1	4676151	4914997	JUNC00000002	1	-	4676151	4914997	255,0,0	2	54,28	0,238818
1	4676151	4977145	JUNC00000003	1	-	4676151	4977145	255,0,0	2	54,28	0,300966
1	4773277	4774364	JUNC00000004	1	-	4773277	4774364	255,0,0	2	59,42	0,1045
1	4774430	4777602	JUNC00000005	6	-	4774430	4777602	255,0,0	2	86,78	0,3094
1	4776703	4777622	JUNC00000006	324	-	4776703	4777622	255,0,0	2	98,98	0,821
1	4777551	4782665	JUNC00000007	249	-	4777551	4782665	255,0,0	2	97,98	0,5016
1	4777564	4778798	JUNC00000008	3	-	4777564	4778798	255,0,0	2	84,51	0,1183
1	4778747	4782629	JUNC00000009	5	-	4778747	4782629	255,0,0	2	51,62	0,3820
1	4782211	4782610	JUNC00000010	3	-	4782211	4782610	255,0,0	2	90,43	0,356
Please help me. Thank you.

**Comment by yang-yangfeng** [comment]
have you tried running the script on another bed just to see if the pipeline is working?

**Comment by Aynur31** [comment]
> have you tried running the script on another bed just to see if the pipeline is working?

Thank you very much for the respond. 
It is solved by removing "? "in the .junc files .

**Comment by malachig** [comment]
Okay, glad to hear that. Closing this issue.
