### ISSUE TITLE
grab single-cell barcodes in junction extract

### ISSUE THREAD

**Issue by yang-yangfeng** [griffithlab/regtools#143]
either have user specify that bam is single-cell or just detect presence of barcodes - if so, add two columns at the end of junction extract 

```
6           ACTTGAC:1, GAATCCA:3, TTTCACG:2
```

**Comment by yang-yangfeng** [comment]
its a bit tricky if we want to follow BED format 

we could use the [bed detail format](https://genome.ucsc.edu/FAQ/FAQformat.html#:~:text=the%20bigBed%20format.-,BED%20detail%20format,links%20from%20the%20details%20pages.) and include the cell count and barcode counts in the 14th column (. in 13th/ID column, or just repeat name?)

another idea is to just create a separate file along with the BED file we are already producing, which contains 3 columns - junction name (matching BED file), cell count, barcode counts

**Comment by malachig** [comment]
Yeah separate file would be fine I guess.  These files could get big so maybe keeping them separate is worth the inconvenience of having two output files...
