### ISSUE TITLE
Is the TCGA exon-exon data still available?

### ISSUE THREAD

**Issue by barreiro-r** [griffithlab/regtools#147]
Hello there,

I'm trying to access the TCGA exon-exon data from [datamed](https://datamed.org/display-item.php?repository=0075&id=AWlw6n1M3J68XfbUFuJP&query=regtools) but I’m getting a `The specified bucket does not exist` error message. Is this data still up?

**Comment by kcotto** [comment]
This data is unfortunately no longer available through datamed due to a lack of funding.
