### ISSUE TITLE
why am I getting an "Error parsing inputs!(2)" error message when using regtools junctions extract?

### ISSUE THREAD

**Issue by skalava23** [griffithlab/regtools#150]
Hello,

I am running the following code:

for bamfile in ls run/geuvadis/*chr1.bam; do
echo Converting $bamfile to $bamfile.junc
samtools index $bamfile
regtools junctions extract -a 8 -m 70 -M 500000 $bamfile -o $bamfile.junc
echo $bamfile.junc >> test_juncfiles.txt
done

-----

This is the message that pops up:

Converting run/geuvadis/RNA.NA06985_CEU.chr1.bam to run/geuvadis/RNA.NA06985_CEU.chr1.bam.junc
Program: regtools
Version: 0.5.2
Usage: regtools junctions extract [options] indexed_alignments.bam
Options:
-a INT Minimum anchor length. Junctions which satisfy a minimum
anchor length on both sides are reported. [8]
-m INT Minimum intron length. [70]
-M INT Maximum intron length. [500000]
-o FILE The file to write output to. [STDOUT]
-r STR The region to identify junctions
in "chr:start-end" format. Entire BAM by default.
-s INT Strand specificity of RNA library preparation
(0 = unstranded, 1 = first-strand/RF, 2, = second-strand/FR). REQUIRED
-t STR Tag used in bam to label strand. [XS]

Error parsing inputs!(2)

------

I have tried following the error message and adding the -s option to the code, but I still get the same error.

What is the reason behind this error message? I am using the example data for leafcutter and trying to convert .bam files to .junc files (this data has been used many times and worked for others). I downloaded regtools via conda for reference.

What could be going wrong? I would appreciate any insight. Thank you!

**Comment by kcotto** [comment]
I think all you need to do is put your BAM file ($bamfile) at the end after all of your options, including `-o $bamfile.junc`. Let me know if this works and if it doesn't, we can problem-solve more.

**Comment by santataRU** [comment]
> I think all you need to do is put your BAM file ($bamfile) at the end after all of your options, including `-o $bamfile.junc`. Let me know if this works and if it doesn't, we can problem-solve more.

Thank you, Kelsy. I encountered the same issue, but your suggestion resolved it!
