### ISSUE TITLE
rmath.dir build error

### ISSUE THREAD

**Issue by kanefos** [griffithlab/regtools#156]
Hi authors,

when following the installation instructions, when I `make` I am able to build variants, bedtools, htslib and samtools fine. however, when I start to build rmath, I encounter this error:

```icc: command line warning #10159: invalid argument for option '--std'```

Any ideas how I can get around this? Apologies if this is a little specific to my institution's HPC cluster but thought I would check here also. Many thanks,

**Comment by kcotto** [comment]
Hi @kanefos, is it possible for you to use our docker image to get around this issue? Available here: https://hub.docker.com/r/griffithlab/regtools. You should be able to use the latest tag.

**Comment by kanefos** [comment]
Ok, I'll try that. Apologies just wanted to check this wasn't an easily-solved error I'd not encountered.
