### ISSUE TITLE
install problem in make file

### ISSUE THREAD

**Issue by changeran** [griffithlab/regtools#157]
After I pull down the regtools on github and finished "cmake .." .however I can't get <makefile> in ./build and failed to make it. How can I solve it?

**Comment by kcotto** [comment]
Hi @changeran, Once you run the following commands:
```
mkdir build
```
you should be able to type `ls` and see the build directory and then `cd` into it to complete the install. Do you see the build directory or did it fail to create with the `mkdir` command?
