### ISSUE TITLE
for long-read RNA-seq data

### ISSUE THREAD

**Issue by changeran** [griffithlab/regtools#158]

**Comment by ErminZ** [comment]
Hello, 

I have a question about junction extract, different junctions are identified between Regtools and NanoSplier. Would you help me to understand why? How does the junctions extract algorithm to cluster and call a junction? Thank you!

The input file is the same BAM file generated by minimap2 for Nanopore data.
1. From Regtools
ref	1180	3212	JUNC00000028	137	?	1180	3212	255,0,0	2	99,51	0,1981
ref	1180	3245	JUNC00000017	658	?	1180	3245	255,0,0	2	99,87	0,1978
ref	1180	6541	JUNC00000030	377	?	1180	6541	255,0,0	2	99,71	0,5290
ref	1180	6608	JUNC00000020	2705	?	1180	6608	255,0,0	2	99,141	0,5287
ref	1198	4144	JUNC00000033	66	?	1198	4144	255,0,0	2	81,46	0,2900
ref	1207	5330	JUNC00000029	89	?	1207	5330	255,0,0	2	72,134	0,3989

2. From NanoSplicer
(1279,   6467) | 2681 (number of reads supporting the junction)
(1279,   3158) | 650
(1279,   6470) | 372
(1283,   6467) | 78

The Illumina data from the same sample also gives different junctions compared to Nanopore sequencing.  
ref	1154	6614	JUNC00000057	4515	+	1154	6614	255,0,0	2	125,147	0,5313
ref	1166	3305	JUNC00000228	932	+	1166	3305	255,0,0	2	113,147	0,1992
ref	1177	6617	JUNC00000232	4481	+	1177	6617	255,0,0	2	102,147	0,5293
ref	1178	3308	JUNC00000083	256	+	1178	3308	255,0,0	2	101,147	0,1983
ref	1178	5343	JUNC00000234	226	+	1178	5343	255,0,0	2	101,147	0,4018
ref	1180	1803	JUNC00000237	13	+	1180	1803	255,0,0	2	99,122	0,501
ref	1180	4245	JUNC00000236	175	+	1180	4245	255,0,0	2	99,147	0,2918
ref	1180	5210	JUNC00000240	469	+	1180	5210	255,0,0	2	99,147	0,3883
ref	1182	6608	JUNC00000243	126	+	1182	6608	255,0,0	2	81,141	0,5285

Thank you in advance!

Best, 
Ermin
