### ISSUE TITLE
regtools 0.6.0

### ISSUE THREAD

**Issue by marie-mille** [griffithlab/regtools#164]
Hello,

I can't find the version I was used to work with :https://github.com/griffithlab/regtools/archive/refs/tags/0.6.0.tar.gz

I can only find  the 0.5.2. Did you remove it ? Is there a reason ? 

Thank you very much.

Best,

**Comment by kcotto** [comment]
Hi @marie-mille, we were cleaning up the repo and this tag was deleted by error. It has now been restored. Thanks for letting us know!
