### ISSUE TITLE
Implement version 1 of an allele specific expression function

### ISSUE THREAD

**Issue by malachig** [griffithlab/regtools#17]
Inputs:
- Transcriptome GTF file
- somatic VCF (SNVs)
- germline VCF (SNPs). This could be germline calls from the individual or simply a dbSNP VCF.  To be this flexible we need to actually check for heterozygous status in the patient.
- tumor RNA-seq BAM
- tumor DNA BAM

We are looking for somatic SNVs that occur near a locus that has a SNP that is heterozygous in the tumor DNA but expression of the SNP in the RNA is not heterozygous.

Outputs:
- One result for each heterozygous SNP position that is within a known transcript(s) where that transcript also has a somatic heterozygous SNV within some neighborhood (user configurable).

**Comment by malachig** [comment]
Called `regtools cis-expression-effects identify` ?

**Comment by malachig** [comment]
Determine relevance of this tool for this task:

GATK ASEReadCounter

https://software.broadinstitute.org/gatk/gatkdocs/org_broadinstitute_gatk_tools_walkers_rnaseq_ASEReadCounter.php

**Comment by gatoravi** [comment]
cis-ase identify is now a module
