### ISSUE TITLE
cannot detect strandedness from cellranger bam file

### ISSUE THREAD

**Issue by ckong1806** [griffithlab/regtools#173]
Hi, I have 10X genomics 3' scRNAseq data that I've processed through cellranger. I have the possorted bam output file and I am trying to run regtools to obtain the splice junctions bed file. Since cellranger uses STAR alignment, there is no info on strand specificity - how do I go about this?

**Comment by SebastianMHJohn** [comment]
Hi,
I have the same issue. I would greatly appreciated any suggestions.
Best wishes

**Comment by kcotto** [comment]
We have an option that you can use `-C` that will use information in the fasta file to try to assign strandedness to reads. More information here: https://regtools.readthedocs.io/en/latest/commands/cis-splice-effects-identify/
