### ISSUE TITLE
Complete documentation of all regtools modules and concepts

### ISSUE THREAD

**Issue by malachig** [griffithlab/regtools#22]
- [ ] Include visual diagrams of key concepts wherever possible
- [ ] cis-ase initial documentation
- [ ] check figures and parameters for cis-splice-effects docs

Updated by @gatoravi ..

**Comment by gatoravi** [comment]
- [ ] cis-ase initial documentation
- [ ] check figures and parameters for cis-splice-effects docs

**Comment by malachig** [comment]
I believe this is now done well.
