### ISSUE TITLE
Make sure somatic variants are trustworthy before running analysis

### ISSUE THREAD

**Issue by gatoravi** [griffithlab/regtools#32]
Perhaps called by more than one variant caller.

**Comment by gatoravi** [comment]
Also use the 'filtered' snv-indel-report file instead of the 'unfiltered' version.

**Comment by gatoravi** [comment]
Ideally, none of the somatic sites should not pass het criteria when regtools is run on the normal sample.

**Comment by malachig** [comment]
Closing this as it is not really about regtools per se but rather about the overall analysis workflow.
