### ISSUE TITLE
cis-splice-effects identify variant info doesn't just show snvs

### ISSUE THREAD

**Issue by yanyangfeng** [griffithlab/regtools#42]
I ran cis-splice-effects identify and the "variant_info" column for one of the junctions was "5:176887555-176887556,5:176887556-176887557", which isn't 2 separate snvs, but one multi-nv with two bases changed. Wasn't sure if this was the intended behavior, so just wanted to make a note of it.

**Comment by malachig** [comment]
hmmm, this might be okay.  Let's keep track of these edge cases and think about the need for general improvements for variant representation here.

**Comment by yanyangfeng** [comment]
wasn't sure if this was the same issue that we were talking about yesterday, but one thing that seemed strange to me was that variants annotate will handle indels 

1	235929575	TTCCTGAAAAAATAAAAAAAACTCTCT	-	.	.	PASS	genes=LYST;transcripts=ENST00000389793,ENST00000389794,ENST00000489585,ENST00000536965;distances=2,2,2,2;annotations=splicing_exonic,splicing_exonic,splicing_exonic,splicing_exonic

but then if you look in the cis-splice-effects output, it just treats this mutation event as a snv
chrom	start	end	name	score	strand	splice_site	acceptors_skipped	exons_skipped	donors_skipped	anchor	known_donor	known_acceptor	known_junction	genes	transcripts	variant_info
1	235926151	235933460	JUNC00000004	14	-	GT-AG	2	1	3	NDA	1	1	0	LYST	ENST00000389793,ENST00000389794,ENST00000489585,ENST00000536965	1:235929574-235929575
1	235929444	235929539	JUNC00000005	11	-	GT-AG	0	0	1	D	1	0	0	LYST	ENST00000489585,ENST00000536965	1:235929574-235929575
