### ISSUE TITLE
cis-splice-effects identify -j option not writing to file

### ISSUE THREAD

**Issue by yanyangfeng** [griffithlab/regtools#47]
-j option will print to stdout, even if -j option is supplied with file name

**Comment by yanyangfeng** [comment]
actually, upon inspecting the log file, it seems like -j option is not even printing bed12 file of aberrant junctions to stdout

**Comment by yanyangfeng** [comment]
Here's the command I ran, and the job successfully completed

/gscmnt/gc2502/griffithlab/yafeng/regtools/build/regtools cis-splice-effects identify -j hcc1395/output/normal_cse_identify_junctions.tsv hcc1395/germline.vcf.gz hcc1395/normal_rna_alignments.bam GRCh37.fa /gscmnt/gc2602/griffithlab/regtools/Homo_sapiens.GRCh37.87.gtf

**Comment by gatoravi** [comment]
Nice catch! Thanks for finding this.
