### ISSUE TITLE
junction numbering cis-splice-effects identify

### ISSUE THREAD

**Issue by yanyangfeng** [griffithlab/regtools#48]
1       235929444       235929539       JUNC00000005    11      -       GT-AG   0       0       1       D       1       0       0       LYST    ENST00000489585,ENST00000536965 1:235929574-235929575

11      71935381        71935824        JUNC00000005    3       +       GT-AG   0       0       1       A       0       1       0       INPPL1  ENST00000540973,ENST00000543234 11:71935825-71935826

Maybe I'm not understanding something, but why are these named the same (JUNC00000005)? 

This is especially strange since this line is present in the output of junctions annotate
11      71935381        71935824        JUNC00175880    3       +       GT-AG   0       0       1       A       0       1       0       INPPL1  ENST00000540973,ENST00000543234

**Comment by gatoravi** [comment]
This needs to be looked into.

**Comment by gatoravi** [comment]
Thanks a lot for catching this @yanyangfeng , I think this should be fixed now!
