### ISSUE TITLE
cis-splice-effects identify -v option sometimes writes columns in wrong order

### ISSUE THREAD

**Issue by yanyangfeng** [griffithlab/regtools#50]
Ran this command twice, on different input files. For the input files that gave me the wrong columns, I reran it and got the same results. The ID column should be the third column but was instead written as the 5th column.

WRONG
regtools cis-splice-effects identify -v hcc1395/output/cse_identify_variants.tsv hcc1395/somatic.vcf.gz hcc1395/tumor_rna_alignments.bam GRCh37.fa /gscmnt/gc2602/griffithlab/regtools/Homo_sapiens.GRCh37.87.gtf

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO
1       16975289        T       A       .       .       PASS    genes=MST1P2;transcripts=ENST00000334429,ENST00000457982;distances=2,2;annotations=splicing_intronic,splicing_intronic
1       17085168        A       T       .       .       PASS    genes=MST1L;transcripts=ENST00000455405,ENST00000544155,ENST00000442552;distances=2,2,2;annotations=splicing_intronic,splicing_intronic,splicing_intronic

RIGHT
regtools cis-splice-effects identify -v hcc1395/output/normal_cse_identify_variants.tsv hcc1395/germline.vcf.gz hcc1395/normal_rna_alignments.bam GRCh37.fa /gscmnt/gc2602/griffithlab/regtools/Homo_sapiens.GRCh37.87.gtf

#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  H_NJ-HCC1395-HCC1395_BL
1       15903   .       G       GC      .       PASS    genes=WASH7P;transcripts=ENST00000438504,ENST00000538476;distances=1,1;annotations=splicing_intronic,splicing_intronic  GT:DP:MQ:FT     1/1:27:14:PASS
1       17501   .       CT      C       .       IndelFilter     genes=WASH7P;transcripts=ENST00000541675;distances=3;annotations=splicing_exonic        GT:DP:MQ:FT     0/0:1017:36:IndelFilter
1       327550  .       C       CG      .       IndelFilter     genes=RP4-669L17.10;transcripts=ENST00000425496;distances=2;annotations=splicing_intronic       GT:DP:MQ:FT     0/0:325:0:IndelFilter

**Comment by yanyangfeng** [comment]
so I noticed that the input vcfs for the two above commands have slightly different header orders

the one that produced the RIGHT output: #CHROM	POS	ID	REF	ALT
the one that produced the WRONG output: #CHROM	POS	REF	ALT	ID

I believe the first one is the standard order. It seems like the script I found to create a vcf from the snvindel report prints the wrong header order 

awk 'BEGIN { print "##fileformat=VCFv4.1\n#CHROM\tPOS\tREF\tALT\tID\tQUAL\tFILTER\tINFO" } !/chrom/ { if($1 !~ /GL/) print $1"\t"$2"\t"$4"\t"$5"\t.\t.\tPASS\t." }'

somehow though, I guess regtools parses the input correctly by looking at the header? but then it prints the columns just based on the order they were in in the input vcf?

**Comment by gatoravi** [comment]
- this might again be dependent on the input VCF, we perhaps need an example to reproduce this.

**Comment by malachig** [comment]
This was a problem caused by a non-spec VCF and therefore isn't really a failing of regtools.
