### ISSUE TITLE
segfault cis-splice-effects-identify -v option

### ISSUE THREAD

**Issue by yanyangfeng** [griffithlab/regtools#53]
Segfaulted on command below. Could be an issue with the vcf I used, which I created by running vcf-concat on snvs and indels vcfs from https://gscweb.gsc.wustl.edu/gscmnt/gc13029/info/model_data/10f85ec821d94e4d924342d7aefd3fa4/builda63f9c1f637f48bf9f66ba60f01a8767/variants/
- any ideas? I did sort and tabix.

/gscmnt/gc2502/griffithlab/yafeng/regtools/build/regtools cis-splice-effects identify -v hcc1395/output/cse_identify_variants.vcf hcc1395/somatic.vcf.gz hcc1395/tumor_rna_alignments.bam GRCh37.fa /gscmnt/gc2602/griffithlab/regtools/Homo_sapiens.GRCh37.87.gtf

**Comment by yanyangfeng** [comment]
be wary of the file name "somatic.vcf.gz" I changed filenames a few times so they may not be referring to the same file in these issues. from #54 on, it should be consistent. In this Issue, somatic.vcf.gz is referring to the file I generated by running vcf-concat on snvs and indels from a somatic validation model for hcc1395.

**Comment by yanyangfeng** [comment]
I generated germline.vcf.gz using the same vcf-concat approach. The difference between germline.vcf.gz and somatic.vcf.gz is somatic.vcf.gz has one additional column at the end- and I remember when running vcf-concat on the snvs and indels from somatic validation, I got a warning saying the column names did not match (which probably explains the presence of the additional column).

the somatic.vcf.gz I refer to here can now be found at: /gscmnt/gc2602/griffithlab/regtools/yafeng/test-regtools/hcc1395/somval/somatic.vcf.gz

the germline.vcf.gz I refer to here can now be found at 
/gscmnt/gc2602/griffithlab/regtools/yafeng/test-regtools/hcc1395/refalign/germline.vcf

**Comment by gatoravi** [comment]
We'll have to try and reproduce this, perhaps an issue with the specific VCF file?

**Comment by yanyangfeng** [comment]
Paths are relative to /gscmnt/gc2602/griffithlab/regtools/yafeng

hcc1395/somval/somatic.vcf.gz was the original vcf that caused the segfault issue when running variants annotate or cis-splice-effects identify with the -v option. 

I then removed the last two columns to create somatic_cut.vcf.gz.  
From here, I removed the next column, "FORMAT" to get somatic_cut_format.vcf.gz. 
Then, I stripped the header down to just the ##fileformat line to get somatic_cut_format_header.vcf.gz.
Finally, I was able to eliminate the segfaulting by setting all values in the INFO column to ".", which you can see in somatic_cut_format_header_info.vcf.gz.

**Comment by malachig** [comment]
The user should be allowed to have info in the INFO column without it causing a problem.  Really as long as the VCF adheres to the spec we should try to support it.  Though I recognize this will be hard to test exhaustively and we may encounter problems over time when new edge cases are encountered.

**Comment by malachig** [comment]
Seems like this is fixed now.  @yanyangfeng testing appears to be working.
