### ISSUE TITLE
variants annotate docs not up to date with command line usage

### ISSUE THREAD

**Issue by yanyangfeng** [griffithlab/regtools#59]
Program:	regtools
Version:	0.2.0
Usage:		regtools variants annotate [options] variants.vcf annotations.gtf
		-e INT	Maximum distance from the start/end of an exon 
			to annotate a variant as relevant to splicing, the variant 
			is in exonic space, i.e a coding variant. [3]
		-i INT	Maximum distance from the start/end of an exon 
			to annotate a variant as relevant to splicing, the variant 
			is in intronic space. [2]
		-I	Annotate variants in intronic space within a transcript(not to be used with -i).
		-E	Annotate variants in exonic space within a transcript(not to be used with -e).
		-o	File to write output to. [STDOUT]
		-S	Don't skip single exon transcripts.

**Comment by gatoravi** [comment]
Thanks for reporting this, I think this is related to #54

**Comment by gatoravi** [comment]
Looks like there's a typo in my PR, needs to be fixed.

**Comment by gatoravi** [comment]
I think this is fixed now:)
