### ISSUE TITLE
acceptors_skipped/donors_skipped not counting correctly

### ISSUE THREAD

**Issue by yang-yangfeng** [griffithlab/regtools#61]
chrom	start	end	name	score	splice_site	acceptors_skipped	exons_skipped	donors_skipped	anchor	genes	variant_info
1	93692006	93697998	JUNC00000014	14	GT-AG	1	0	1	D	CCDC18	1:93692005-93692006

This junction is marked as D, and upon examination in IGV that's correct. I also agree that there is 1 acceptor skipped and 0 exons skipped. However, it doesn't make sense to me why regtools is saying there was 1 donor skipped. I did run this sample with the gtf that contained all the other stuff besides the exons (transcripts, CDS, etc) but if you look at the gtf track it doesn't seem like any of that would explain it either.

<img width="1356" alt="screen shot 2017-03-30 at 4 48 57 pm" src="https://cloud.githubusercontent.com/assets/16638655/24527888/cb1ea572-1569-11e7-868c-0644706078f3.png">

<img width="1354" alt="screen shot 2017-03-30 at 4 49 53 pm" src="https://cloud.githubusercontent.com/assets/16638655/24527889/cd10914c-1569-11e7-9cb9-d54b068d2755.png">

**Comment by malachig** [comment]
Hi @yanyangfeng.  Can we see a zoomed out version of this where all of JUNC00000014 is visible at once?

**Comment by yanyangfeng** [comment]
![ccdc18_all](https://cloud.githubusercontent.com/assets/16638655/24533989/e93825fc-1590-11e7-880c-919bd712a941.png)

**Comment by malachig** [comment]
I agree, I see an acceptor skipped, no exons skipped, and no donors skipped.  Unless somehow a feature is not being shown in this GTF track...

**Comment by malachig** [comment]
Actually if you zoom in all the way on the left side, it looks like "93692006" does cover the last base of that exon.  Meaning that the donor is being skipped in a sense.  But that seems like a off by one error perhaps?

**Comment by yanyangfeng** [comment]
<img width="1354" alt="screen shot 2017-03-30 at 10 03 06 pm" src="https://cloud.githubusercontent.com/assets/16638655/24534618/bc8b4382-1594-11e7-83a6-1e39001ea2a0.png">

Looks to me like it just stops at the exon, without covering any of it. It is a little weird how IGV converts the 0 based coordinates you load to 1 based coordinates when you click on the junction.

**Comment by malachig** [comment]
Hey @gatoravi.  I believe this is the last outstanding bug we wanted to tackle before freezing for a manuscript.  Any chance you could take a look at this one please?

**Comment by yang-yangfeng** [comment]
Resolved by PR #94
