### ISSUE TITLE
Expose options of variants-annotate in cis-splice-effects identify

### ISSUE THREAD

**Issue by gatoravi** [griffithlab/regtools#69]

**Comment by malachig** [comment]
Hey @gatoravi , if you have a moment, this feature would be helpful for the analysis tests we are doing right now.

**Comment by gatoravi** [comment]
Sure thing, I'm on it now!

**Comment by gatoravi** [comment]
Hey guys, try out master now and see if it has the options that you'd like, I'll leave the pull request open in case we need more options to be exposed.

**Comment by malachig** [comment]
Great. thanks @gatoravi. @yanyangfeng can you try this out asap please?

**Comment by yanyangfeng** [comment]
Tested this and it's working now, thanks @gatoravi! Closing.
