### ISSUE TITLE
gene_id addition request

### ISSUE THREAD

**Issue by frankbioinfo** [griffithlab/regtools#76]
While using regtools annotate on rna seq bams, any reason why ensembl gene_ids are not listed next to gene_name and transcript ids?

**Comment by frankbioinfo** [comment]
I'll close the issue if this is not relevant or out of scope. I thought this could a good feature to add the gene_id  by collapsing the junctions to gene they belong.

**Comment by frankbioinfo** [comment]
Closing feature request

**Comment by zlskidmore** [comment]
@frankbioinfo apologies for the delayed response. I think it's a good idea to provide this information, we will look into adding this functionality.

**Comment by frankbioinfo** [comment]
Thanks!
