### ISSUE TITLE
junctions annotate not working with non-stranded BAMs

### ISSUE THREAD

**Issue by berntpopp** [griffithlab/regtools#78]
Hey,
Thanks for this great tool!

Unfortunatelly I can not annotate the bed file produced by "regtools junctions extract" with any gtf (gencode, ensembl). You can find a sample file for debugging here: https://www.dropbox.com/s/nljemq72hpggr07/regtools.bed?dl=0.

BAM files of a non-stranded cDNA were generated with STAR-aligner. The problem seems to be related to the non-strandedness. If I arbitrarily change the "?" in the strand column to "+" about half of the genes get annotated.
I think this should be easy to fix by using the strand information from the GTF file and not from the bed file.

Best regards,
Bernt

**Comment by gatoravi** [comment]
Hi, 
Thanks for reporting this, how are you annotating the BED file? Currently we use the information from the reads in the BAM file to infer the strand of a junction, are you suggesting we don't do that?
Avi

**Comment by berntpopp** [comment]
Hey,

For junction calling and annotation I used sstandard commands as described onthe "readthedocs" site. For the ´regtools junctions annotate´ command I tried the GENCODE v19 and Ensemble GTF files as input. Also the command works when i change the "?" to "+" (example file: https://www.dropbox.com/s/6wk3nwd3egvyvi8/regtools.annotate.bed?dl=0) (so GTF files are not the cause of the problem).

For me it would be usefull if the strand information of the reads would not be necessary for the annotation step or if there would be a way to override this behaviour and handle unstranded libraries. I don't know if it can happen that a described junction is on the wrong strand?

Best regards,
Bernt

**Comment by malachig** [comment]
This is related to #70

**Comment by berntpopp** [comment]
Any news on this? I would very much like to use this tool for a project, but this little problem hinders the application to or data.
Seems there has been no commit since some time?

Best regards,
Bernt

**Comment by yang-yangfeng** [comment]
Hi @berntpopp, sorry it has taken so long to find answer for this - we've had a bit of a personnel change that hindered our progress. Hopefully you are still interested in applying regtools to your data. Of course, unstranded data is not ideal. For unstranded data, Regtools determines the strand of each read pair based on the the XS attribute of the bam line. STAR does not include this in their alignments by default. If you want to use STAR, the work around is to realign with the --outSAMstrandfield <intron motif> option (see section 4.2.3 of the [STAR manual](http://labshare.cshl.edu/shares/gingeraslab/www-data/dobin/STAR/STAR.posix/doc/STARmanual.pdf)). Just note that this will filter out any reads for which STAR cannot guess a strand based on canonical intron motifs.

**Comment by yang-yangfeng** [comment]
addressed by PR #91
