### ISSUE TITLE
Variants annotate error

### ISSUE THREAD

**Issue by MagicPoon** [griffithlab/regtools#82]
Hi,
I ran the regtools variants annotate, then it showed 

[E::bcf_hdr_read] invalid BCF2 magic string
Unable to read header.Segmentation fault

How to solve it?
Thanks

**Comment by malachig** [comment]
Can you provide the complete command you attempted?

**Comment by MagicPoon** [comment]
regtools variants annotate T37.nh2.all.vcf gencode.v26lift37.annotation.gtf

Program:        regtools
Version:        0.4.0
Variant file: T37.nh2.all.vcf
GTF file: gencode.v26lift37.annotation.gtf
Output vcf file: NA
Intronic min distance: 2
Exonic min distance: 3
[E::bcf_hdr_read] invalid BCF2 magic string
Unable to read header.Segmentation fault

**Comment by malachig** [comment]
Is your VCF in binary format despite the .vcf suffix?

**Comment by MagicPoon** [comment]
It's in binary format

**Comment by malachig** [comment]
I don't think we support binary format.  Try converting to plain text.  If that fixes the problem we'll create an issue to add binary VCF support as a feature request.

**Comment by MagicPoon** [comment]
But it still can't work...

**Comment by malachig** [comment]
The same error?

**Comment by MagicPoon** [comment]
yes

**Comment by malachig** [comment]
There seem to be many reports online of this error `[E::bcf_hdr_read] invalid BCF2 magic string` for various tools.  It sounds like it may have to do with version compatibility issues between samtools/htslib and bcftools.  How did you create this BCF file?  How did you convert it back to plain text VCF?

**Comment by malachig** [comment]
@MagicPoon did you find a solution to this problem?

**Comment by yang-yangfeng** [comment]
@MagicPoon, could you try compressing your vcf with bgzip and then running tabix on it?

**Comment by MagicPoon** [comment]
Oh... I carried out with another tool, thank you all!
