### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by Annonymousac** [griffithlab/regtools#90]
When I tried the basic command of Regtools it was showing the following error: 
![a](https://user-images.githubusercontent.com/32244246/32733537-8796a4b2-c8b5-11e7-9938-33362c3fd130.png)

regtools: command not found

**Comment by yang-yangfeng** [comment]
where is your regtools installed? it looks like you accidentally cd'd into your home directory and then tried running regtools - if you haven't pointed to the regtools binary in your bash profile or by using an absolute path, you need to be in regtools/build. 

Try cd ~/regtools/build and then regtools OR ~/regtools/build/regtools

**Comment by yang-yangfeng** [comment]
Hi @Annonymousac, I am assuming this is resolved and will close the issue for now - but feel free to reopen if needed!
